# 사용할 이미지 설정
FROM mysql:latest

# 작업 디렉토리 설정
WORKDIR /mysql

# 환경 변수 설정 (필요에 따라 수정)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# 외부 설정 파일 복사
COPY ./mysql-config/my.cnf /etc/mysql/conf.d/my.cnf

# 포트 설정
EXPOSE 3306
